version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.0
      - image: redis
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      JDK_VERSION: 17
      TERM: dumb
      TZ: "Asia/Tokyo"
      YARN_SILENT: 1
    steps:
      - checkout
      - run:
          name: Checkout submodule
          command: |
            git submodule update --init
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Test
          command: |
            ./gradlew check jacocoTestReport
      - codecov/upload
      - run:
          name: Build
          command: |
            ./gradlew clean :app:bootJar
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - heroku/install
      - run:
          name: Deployment
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ]; then
              ./.circleci/setup-retry.sh

              retry -- heroku plugins:install java
              retry -- heroku deploy:jar \
                --jar app/build/libs/app.jar \
                --jdk $JDK_VERSION \
                --app $HEROKU_APP
            fi

