# Spring Framework
# ---------------------------

logging:
  level:
    moe.pine.stkrep: DEBUG

spring:
  redis:
    database: 0


# Job Scheduler
# ---------------------------

scheduling:
  enabled: false


# Google Sheets
# ---------------------------

sheets:
  credentials-path: 'classpath:gcp-credentials.json'
  application-name: stkrep
  forecast-sheets:
    spreadsheet-id: 'spreadsheet-id'
    codes-range: 'codes-range'
    result-sheet-name: 'Result'
    result-offset-y: 1
